spring:
  application:
    name: msclientes
  cloud:
    config:
      enabled: false
    
server:
  port: 0
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance-id:${random.value}}